# Generated by Django 4.1.2 on 2022-11-08 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_empleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='Cargo',
            field=models.CharField(blank=True, help_text='Cargo', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='Oficina',
            field=models.CharField(help_text='Oficina', max_length=150, null=True),
        ),
    ]
