# Generated by Django 4.1.2 on 2022-12-12 04:51

import base.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0004_empleado_foto_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='Foto_Perfil',
            field=models.ImageField(blank=True, null=True, upload_to=base.models.upload_to),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
            preserve_default=False,
        ),
    ]
