# Generated by Django 4.1.2 on 2022-12-12 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_estatus_employed_empleado_empleado_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='Email',
            field=models.EmailField(help_text='Correo', max_length=254),
        ),
    ]
