# Generated by Django 4.1.2 on 2022-12-12 05:52

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_empleado_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codigo_CUI', models.CharField(help_text='Codigo CUI', max_length=7)),
                ('Codigo_SNIP', models.CharField(help_text='Codigo SNIP', max_length=8, null=True)),
                ('Nombre', models.CharField(help_text='Nombre Proyecto', max_length=1000, null=True)),
                ('Foto_Perfil', models.ImageField(null=True, upload_to=base.models.upload_to_proyecto_perfil)),
                ('Fecha_Registro', models.DateField(verbose_name='Fecha de Registro')),
                ('Fecha_Inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('Fecha_Fin', models.DateField(verbose_name='Fecha Fin')),
            ],
        ),
    ]
