# Generated by Django 4.1.2 on 2022-12-12 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_proyecto_codigo_snip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='Fecha_Registro',
            field=models.DateField(blank=True, verbose_name='Fecha de Registro'),
        ),
    ]
