# Generated by Django 4.1.2 on 2022-12-12 06:18

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_proyecto_fecha_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='Codigo_SNIP',
            field=models.CharField(blank=True, help_text='Codigo SNIP', max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='Fecha_Fin',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Fin'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='Fecha_Inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='Foto_Perfil',
            field=models.ImageField(blank=True, null=True, upload_to=base.models.upload_to_proyecto_perfil),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='Nombre',
            field=models.CharField(help_text='Nombre Proyecto', max_length=1000),
        ),
    ]
