# Generated by Django 4.1.2 on 2022-12-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_proyecto_codigo_snip_alter_proyecto_fecha_fin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='Nombre',
            field=models.TextField(help_text='Nombre Proyecto'),
        ),
    ]
