# Generated by Django 4.1.2 on 2022-12-13 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_proyecto_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Denominacion', models.CharField(help_text='Denominación', max_length=100)),
            ],
        ),
    ]
