# Generated by Django 4.1.2 on 2022-12-13 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='sector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.sector'),
        ),
    ]
