# Generated by Django 4.1.2 on 2022-12-13 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_proyecto_sector'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado_Inversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Estado_Actual', models.CharField(help_text='Denominación', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.sector'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='estado_inversion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.estado_inversion'),
        ),
    ]
