# Generated by Django 4.1.2 on 2022-12-14 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_alter_empleado_options_alter_proyecto_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='sector',
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='name', max_length=100)),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.sector')),
            ],
            options={
                'verbose_name': 'Tipo de Inversion',
                'verbose_name_plural': 'tipos de Inversion',
                'db_table': 'Tipo',
            },
        ),
        migrations.AddField(
            model_name='proyecto',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.tipo'),
        ),
    ]
