# Generated by Django 4.1.2 on 2022-12-14 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_remove_proyecto_sector_tipo_proyecto_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubigeo', models.CharField(help_text='ubigeo', max_length=6)),
                ('distrito', models.CharField(blank=True, help_text='Distrito', max_length=50, null=True)),
                ('provincia', models.CharField(blank=True, help_text='Provincia', max_length=50, null=True)),
                ('departamento', models.CharField(blank=True, help_text='DEpartamento', max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Distrito',
                'verbose_name_plural': 'Distritos',
                'db_table': 'ciudad',
            },
        ),
    ]
