# Generated by Django 4.1.2 on 2022-12-15 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_proyecto_modalidad_ejecucion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='ubicacion',
        ),
        migrations.CreateModel(
            name='Beneficiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descripcion', models.TextField(blank=True, help_text='Nombre Proyecto', null=True)),
                ('cantidad', models.IntegerField(blank=True, help_text='Cantidad', null=True)),
                ('Proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.proyecto')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.ciudad')),
            ],
            options={
                'verbose_name': 'Modalidad de Ejecucion',
                'verbose_name_plural': 'Modalidades de Ejecucion',
                'db_table': 'Beneficiario',
            },
        ),
    ]
