# Generated by Django 4.1.2 on 2022-12-15 23:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_remove_proyecto_ubicacion_beneficiario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Situacion_inversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descripcion', models.TextField(blank=True, help_text='Descripcion del componente', null=True)),
                ('Fecha_Modificado', models.DateTimeField(default=datetime.datetime.now, help_text='Fecha de ultima actualizacion')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.proyecto')),
            ],
            options={
                'verbose_name': 'Situacion de Inversion',
                'verbose_name_plural': 'Situaciones de Inversion',
                'db_table': 'Situacion_inversion',
            },
        ),
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.TextField(help_text='Componente de Inversion')),
                ('Descripcion', models.TextField(blank=True, help_text='Descripcion del componente', null=True)),
                ('Costo_Total', models.DecimalField(decimal_places=2, help_text='Costo total Actualizado', max_digits=9)),
                ('Dev_Acumulado', models.DecimalField(decimal_places=2, help_text='Devengado Acumulado', max_digits=9)),
                ('Avance_porcentaje', models.DecimalField(decimal_places=2, help_text='Porcentaje de avance', max_digits=3)),
                ('Fecha_Actualizado', models.DateTimeField(default=datetime.datetime.now, help_text='Fecha de ultima actualizacion')),
                ('Comentario', models.TextField(help_text='Comentario sobre el componente')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.proyecto')),
            ],
            options={
                'verbose_name': 'Componente',
                'verbose_name_plural': 'Componentes',
                'db_table': 'Componente',
            },
        ),
    ]
