# Generated by Django 4.1.2 on 2022-12-19 15:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_situacion_inversion_componente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componente',
            name='Avance_porcentaje',
            field=models.DecimalField(decimal_places=2, help_text='Porcentaje de avance', max_digits=5),
        ),
        migrations.AlterField(
            model_name='componente',
            name='Costo_Total',
            field=models.DecimalField(decimal_places=2, help_text='Costo total Actualizado', max_digits=11),
        ),
        migrations.AlterField(
            model_name='componente',
            name='Dev_Acumulado',
            field=models.DecimalField(decimal_places=2, help_text='Devengado Acumulado', max_digits=11),
        ),
        migrations.CreateModel(
            name='PIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Monto_programado', models.DecimalField(decimal_places=2, help_text='Monto_asignado', max_digits=11)),
                ('Year', models.DateTimeField(default=datetime.datetime.now, help_text='Año Asignado')),
                ('Monto_programado_01', models.DecimalField(decimal_places=2, help_text='Monto_asignado_enero', max_digits=11)),
                ('Monto_programado_02', models.DecimalField(decimal_places=2, help_text='Monto_asignado_febrero', max_digits=11)),
                ('Monto_programado_03', models.DecimalField(decimal_places=2, help_text='Monto_asignado_marzo', max_digits=11)),
                ('Monto_programado_04', models.DecimalField(decimal_places=2, help_text='Monto_asignado_abril', max_digits=11)),
                ('Monto_programado_05', models.DecimalField(decimal_places=2, help_text='Monto_asignado_mayo', max_digits=11)),
                ('Monto_programado_06', models.DecimalField(decimal_places=2, help_text='Monto_asignado_junio', max_digits=11)),
                ('Monto_programado_07', models.DecimalField(decimal_places=2, help_text='Monto_asignado_julio', max_digits=11)),
                ('Monto_programado_08', models.DecimalField(decimal_places=2, help_text='Monto_asignado_agosto', max_digits=11)),
                ('Monto_programado_09', models.DecimalField(decimal_places=2, help_text='Monto_asignado_setiembre', max_digits=11)),
                ('Monto_programado_10', models.DecimalField(decimal_places=2, help_text='Monto_asignado_octubre', max_digits=11)),
                ('Monto_programado_11', models.DecimalField(decimal_places=2, help_text='Monto_asignado_noviembre', max_digits=11)),
                ('Monto_programado_12', models.DecimalField(decimal_places=2, help_text='Monto_asignado_diciembre', max_digits=11)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.proyecto')),
            ],
            options={
                'verbose_name': 'PIA',
                'verbose_name_plural': 'PIAs',
                'db_table': 'PIA',
            },
        ),
    ]
