# Generated by Django 4.1.2 on 2022-12-19 15:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_alter_componente_avance_porcentaje_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PIM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Monto_actualizado', models.DecimalField(decimal_places=2, help_text='Monto_actualizado', max_digits=11)),
                ('Year', models.DateTimeField(default=datetime.datetime.now, help_text='Año Asignado')),
                ('Monto_actualizado_01', models.DecimalField(decimal_places=2, help_text='Monto_actualizado_enero', max_digits=11)),
                ('Monto_actualizado_02', models.DecimalField(decimal_places=2, help_text='Monto_actualizado_febrero', max_digits=11)),
                ('Monto_actualizado_03', models.DecimalField(decimal_places=2, help_text='Monto_actualizado_marzo', max_digits=11)),
                ('Monto_actualizado_04', models.DecimalField(decimal_places=2, help_text='Monto_actualizado_abril', max_digits=11)),
                ('Monto_actualizado_05', models.DecimalField(decimal_places=2, help_text='Monto_actualizado_mayo', max_digits=11)),
                ('Monto_actualizado_06', models.DecimalField(decimal_places=2, help_text='Monto_actualizado_junio', max_digits=11)),
                ('Monto_actualizado_07', models.DecimalField(decimal_places=2, help_text='Monto_actualizado_julio', max_digits=11)),
                ('Monto_actualizado_08', models.DecimalField(decimal_places=2, help_text='Monto_actualizado_agosto', max_digits=11)),
                ('Monto_actualizado_09', models.DecimalField(decimal_places=2, help_text='Monto_actualizado_setiembre', max_digits=11)),
                ('Monto_actualizado_10', models.DecimalField(decimal_places=2, help_text='Monto_actualizado_octubre', max_digits=11)),
                ('Monto_actualizado_11', models.DecimalField(decimal_places=2, help_text='Monto_actualizado_noviembre', max_digits=11)),
                ('Monto_actualizado_12', models.DecimalField(decimal_places=2, help_text='Monto_actualizado_diciembre', max_digits=11)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.proyecto')),
            ],
            options={
                'verbose_name': 'PIM',
                'verbose_name_plural': 'PIMs',
                'db_table': 'PIM',
            },
        ),
    ]
