# Generated by Django 4.1.2 on 2022-12-20 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_alter_pim_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beneficiario',
            options={'verbose_name': 'beneficiario', 'verbose_name_plural': 'beneficiarios'},
        ),
        migrations.RemoveField(
            model_name='componente',
            name='Avance_porcentaje',
        ),
        migrations.RemoveField(
            model_name='componente',
            name='Comentario',
        ),
        migrations.RemoveField(
            model_name='componente',
            name='Costo_Total',
        ),
        migrations.RemoveField(
            model_name='componente',
            name='Descripcion',
        ),
        migrations.RemoveField(
            model_name='componente',
            name='Dev_Acumulado',
        ),
        migrations.RemoveField(
            model_name='componente',
            name='Fecha_Actualizado',
        ),
        migrations.AddField(
            model_name='componente',
            name='Componente_Fisico',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Devengado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_Anual', models.DecimalField(decimal_places=2, help_text='Monto_actualizado', max_digits=11)),
                ('Year', models.CharField(help_text='Año asignado', max_length=4)),
                ('Monto_devengado_01', models.DecimalField(decimal_places=2, help_text='Monto_devengado_enero', max_digits=11)),
                ('Monto_devengado_02', models.DecimalField(decimal_places=2, help_text='Monto_devengado_febrero', max_digits=11)),
                ('Monto_devengado_03', models.DecimalField(decimal_places=2, help_text='Monto_devengado_marzo', max_digits=11)),
                ('Monto_devengado_04', models.DecimalField(decimal_places=2, help_text='Monto_devengado_abril', max_digits=11)),
                ('Monto_devengado_05', models.DecimalField(decimal_places=2, help_text='Monto_devengado_mayo', max_digits=11)),
                ('Monto_devengado_06', models.DecimalField(decimal_places=2, help_text='Monto_devengado_junio', max_digits=11)),
                ('Monto_devengado_07', models.DecimalField(decimal_places=2, help_text='Monto_devengado_julio', max_digits=11)),
                ('Monto_devengado_08', models.DecimalField(decimal_places=2, help_text='Monto_devengado_agosto', max_digits=11)),
                ('Monto_devengado_09', models.DecimalField(decimal_places=2, help_text='Monto_devengado_setiembre', max_digits=11)),
                ('Monto_devengado_10', models.DecimalField(decimal_places=2, help_text='Monto_devengado_octubre', max_digits=11)),
                ('Monto_devengado_11', models.DecimalField(decimal_places=2, help_text='Monto_devengado_noviembre', max_digits=11)),
                ('Monto_devengado_12', models.DecimalField(decimal_places=2, help_text='Monto_devengado_diciembre', max_digits=11)),
                ('PIM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.pim')),
            ],
            options={
                'verbose_name': 'Devengado',
                'verbose_name_plural': 'Devengados',
                'db_table': 'devengado',
            },
        ),
        migrations.CreateModel(
            name='Costo_general',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Costo_total', models.DecimalField(decimal_places=2, help_text='Monto_actualizado', max_digits=11)),
                ('Devengado_acumulado', models.DecimalField(decimal_places=2, help_text='Devengado_acumulado', max_digits=11)),
                ('certificacion_Acumulada', models.DecimalField(decimal_places=2, help_text='certificacion_acumulada', max_digits=11)),
                ('Last_Year', models.CharField(help_text='Ultimo Año actualizado', max_length=4)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.proyecto')),
            ],
            options={
                'verbose_name': 'Costo general',
                'verbose_name_plural': 'Costos generales',
                'db_table': 'costo_general',
            },
        ),
        migrations.CreateModel(
            name='Certificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_Anual', models.DecimalField(decimal_places=2, help_text='Monto_actualizado', max_digits=11)),
                ('Year', models.CharField(help_text='Año asignado', max_length=4)),
                ('Monto_certificado_01', models.DecimalField(decimal_places=2, help_text='Monto_certificado_enero', max_digits=11)),
                ('Monto_certificado_02', models.DecimalField(decimal_places=2, help_text='Monto_certificado_febrero', max_digits=11)),
                ('Monto_certificado_03', models.DecimalField(decimal_places=2, help_text='Monto_certificado_marzo', max_digits=11)),
                ('Monto_certificado_04', models.DecimalField(decimal_places=2, help_text='Monto_certificado_abril', max_digits=11)),
                ('Monto_certificado_05', models.DecimalField(decimal_places=2, help_text='Monto_certificado_mayo', max_digits=11)),
                ('Monto_certificado_06', models.DecimalField(decimal_places=2, help_text='Monto_certificado_junio', max_digits=11)),
                ('Monto_certificado_07', models.DecimalField(decimal_places=2, help_text='Monto_certificado_julio', max_digits=11)),
                ('Monto_certificado_08', models.DecimalField(decimal_places=2, help_text='Monto_certificado_agosto', max_digits=11)),
                ('Monto_certificado_09', models.DecimalField(decimal_places=2, help_text='Monto_certificado_setiembre', max_digits=11)),
                ('Monto_certificado_10', models.DecimalField(decimal_places=2, help_text='Monto_certificado_octubre', max_digits=11)),
                ('Monto_certificado_11', models.DecimalField(decimal_places=2, help_text='Monto_certificado_noviembre', max_digits=11)),
                ('Monto_certificado_12', models.DecimalField(decimal_places=2, help_text='Monto_certificado_diciembre', max_digits=11)),
                ('PIM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.pim')),
            ],
            options={
                'verbose_name': 'Certificación',
                'verbose_name_plural': 'Certificaciones',
                'db_table': 'certificacion',
            },
        ),
    ]
