# Generated by Django 4.1.2 on 2022-12-20 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_alter_beneficiario_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uei',
            name='Opmi',
            field=models.CharField(help_text='OPMI', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='uei',
            name='Unidad_Ejecutora_de_Inversiones',
            field=models.CharField(help_text='Unidad Ejecutora de Inversiones(UEI)', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='uei',
            name='Unidad_Formuladora',
            field=models.CharField(help_text='Unidad Formuladora', max_length=150, null=True),
        ),
    ]
