# Generated by Django 4.1.2 on 2022-12-28 23:53

import base.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0034_alter_proyecto_codigo_cui'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(help_text='Evento ', max_length=500)),
                ('Discripción', models.TextField(help_text='Discripción')),
                ('Fecha_Evento', models.DateField(blank=True, null=True, verbose_name='Fecha de Evento')),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.proyecto')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'db_table': 'actividad',
            },
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(help_text='Evento ', max_length=500)),
                ('Permiso_Activo', models.BooleanField(default=True)),
                ('Permiso_proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.proyecto')),
                ('Permiso_unidad_ejecutora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.uei')),
            ],
            options={
                'verbose_name': 'Permiso',
                'verbose_name_plural': 'Permisos',
                'db_table': 'Permiso',
            },
        ),
        migrations.CreateModel(
            name='User_Permiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha_Inicio', models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio')),
                ('User_Permiso_Activo', models.BooleanField(default=True)),
                ('permiso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.permiso')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User_Permiso',
                'verbose_name_plural': 'User Permisos',
                'db_table': 'user-permiso',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Archivo', models.FileField(blank=True, null=True, upload_to=base.models.upload_to_evidencia)),
                ('Url', models.URLField(blank=True, help_text='Link', max_length=500, null=True)),
                ('Img', models.BooleanField(default=False)),
                ('Video', models.BooleanField(default=False)),
                ('actividad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.actividad')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'db_table': 'Evento',
            },
        ),
    ]
